### ISSUE TITLE
RFC: add failIfNoPactsFound flag to Provider tests

### ISSUE THREAD

**Issue by arnoldsi-payo** [pact-foundation/pact-net#507] opened 2024-06-18 11:23 UTC
Following the discussion here: 
https://pact-foundation.slack.com/archives/C9UTHV2AD/p1718604649363489?thread_ts=1717870729.985429&cid=C9UTHV2AD

Pact.Net is missing the "failIfNoPactsFound" flag, which exists in the nodeJS library. 
Without this crucial functionality, we are currently unable to conduct provider tests unless the consumer pacts are published to the broker, which is a significant limitation.

It's a very important feature (in my opinion), especially for messaging (async) testing.

**Comment by YOU54F** [comment] 2024-06-18 15:39
dupe of https://github.com/pact-foundation/pact-net/issues/462

**Comment by adamrodger** [comment] 2024-06-19 08:56
Duplicate of https://github.com/pact-foundation/pact-net/issues/462

**Comment by adamrodger** [comment] 2024-07-16 17:30
Sorry, that should've been closed when marked as duplicate

**Closed** 2024-07-16 17:30 UTC
Labels: triage
