### ISSUE TITLE
Please share examples with .NET 6 new hosting model without Startup.cs

### ISSUE THREAD

**Issue by fingers10** [pact-foundation/pact-net#481] opened 2023-10-27 01:28 UTC
I'm planning to write PACT provider test. But all the examples mentioned in repo uses Startup.cs hosting model.

My .NET 6+ project is using new hosting model which has only Program.cs and no Startup.cs

Please can anyone share example with new hosting model?

**Comment by mefellows** [comment] 2023-10-27 04:15
I don't know .NET enough to tell you how, but the main thing you need to do is start your service so that it is accessible over an HTTP port (e.g. port `80`). If you can do that, then that's all that matters.

That is, how you start your service is irrelevant - Pact just communicates with it over HTTP.

**Comment by basdijkstra** [comment] 2023-10-27 05:10
You mean you’re using a minimal API rather than the traditional controller-based APIs? I wouldn’t call that new versus old but rather a different design type, but I digress.

I’d like to see if there’s an easy way to do this, too. In my example here: https://github.com/basdijkstra/introduction-to-contract-testing-dotnet/tree/main/AddressProvider I had to wrap my API in a Startup / Program construct to enable adding the Pact service URL and ProviderStateMiddleware in my tests.

If there’s an easier way to do that, I’d love to learn more.

**Comment by fingers10** [comment] 2023-10-27 10:53
@basdijkstra I'm using new hosting model which has only Program.cs. And I'm not using minimal api. I'm using normal controllers. A simple .NET 7 API template with normal controller is what I'm using.

**Comment by adamrodger** [comment] 2023-10-27 21:10
This is a duplicate of #444

**Closed** 2023-10-27 21:10 UTC
