### ISSUE TITLE
Support Publishing Results Using URI Sources

### ISSUE THREAD

**Issue by adamrodger** [pact-foundation/pact-net#392] opened 2022-05-26 19:01 UTC
## Existing State

Currently, PactNet only supports publishing verification results using the Broker source, like this:

```csharp
string version = Environment.GetEnvironmentVariable("GIT_SHA");
string branch = Environment.GetEnvironmentVariable("GIT_BRANCH");
string username = Environment.GetEnvironmentVariable("BROKER_USERNAME");
string password = Environment.GetEnvironmentVariable("BROKER_PASSWORD");

verifier.ServiceProvider("My API", this.fixture.ServerUri)
        .WithPactBrokerSource(new Uri("https://broker.example.org"), options =>
        {
            options.EnablePending()
                   .ConsumerVersionSelectors(new ConsumerVersionSelector { MainBranch = true })
                   .PublishResults(version, publish => publish.ProviderBranch(branch)); // 👈 enable publishing results
        })
        .Verify();
```

## Proposed API

It should be possible to publish verification results to a Pact Broker when using a URI source, as recommended in some of the [Pact CI/CD setup guides](https://docs.pact.io/pact_nirvana). In these flows, a verifier is triggered from a webhook with the URI of the pact that has changed (instead of all pacts). The verifier should then pull the pact from this URI, verify just this one pact, then publish results back to the broker.

The API would be something like:

```csharp
Uri uri = new Uri(Environment.GetEnvironmentVariable("PACT_URI")); // 👈 from the webhook

verifier.ServiceProvider("My API", this.fixture.ServerUri)
        .WithUriSource(uri, options =>
        {
            options.BasicAuthentication(username, password)
                   .PublishResults(version, publish => publish.ProviderBranch(branch)); // 👈 new
        })
        .Verify();
```

## Open Questions

- How is the broker URI discovered?
    - Is it inferred from the webhook URI itself?
    - Is that even safe?
    - What if you retrieve the pact from any old URI and then try to publish results as if it's a broker?
    - Should we force people to provide the broker URI instead? That seems the safest solution
    - **Answer**: The pact file itself will contain a link to publish verification results if it was retrieved from a Pact Broker. Thus, if the link is missing then the publish option shouldn't do anything, and if it is present then publshing can be safely achieved.
- What support is available in the FFI for this?
    - **Answer**: None currently. See the tracking issue: https://github.com/pact-foundation/pact-reference/issues/199
- Should other types of sources be supported as well? e.g. could a CI job put the pact file somewhere, then a file source verifies it and publishes the verification results?
    - **Answer**: No, at least not for now

**Comment by adamrodger** [comment] 2022-05-26 20:01
Note that this feature would need FFI changes because the current FFI only supports publishing results when using a broker source:

https://github.com/pact-foundation/pact-reference/blob/e32caf8defd399029dcdf09c5d9298a1fe71d75a/rust/pact_verifier/src/lib.rs#L1207-L1228

It has the same problem as in my design questions above - you don't know the broker URL, and really it's not safe (and certainly not robust) to assume it's just the host from the URI source itself.

**Comment by bethesque** [comment] 2022-05-27 06:37
> How is the broker URI discovered?

The URL to publish the verification results is in the [verification results HAL relation of the pact itself](https://github.com/pact-foundation/pact_broker/blob/master/lib/pact_broker/doc/views/pact/publish-verification-results.markdown), and is exactly the same no matter how the pact is retrieved (via direct URL, or from the 'pacts for verification' endpoint). The ruby code base just checks to see if the appropriate HAL relation (`pb:publish-verification-results`) is present - it doesn't care how it was retrieved. It would work even if the pact came from a file, as long as the relation was there.

It is news to me that a verification result cannot be published for a pact that is retrieved by URI in the rust impl. If that is the case, we need to fix that ASAP, because there's no point to running a webhook to get verification results from a provider if you can't publish the verification results.

**Comment by adamrodger** [comment] 2022-05-27 13:54
I think using the HAL endpoint is a bit chicken and egg.

The URI source could be given any old URI. It could be a link to a GitHub repo containing pact files, or a random web server, or anything really. 

You have to already know that it's a pact broker in order to use HAL, and if you do then we've got no problem anyway 😁

The problem is knowing whether the URI even represents a broker or not, plus the FFI changes to publish to a non-broker source.

**Comment by bethesque** [comment] 2022-06-01 03:54
> The problem is knowing whether the URI even represents a broker or not

You cannot tell this from the URI alone - but you can tell from the pact content. If it is from the pact broker, then it will have the path `$['_links']['pb:publish-verification-results']['href']` in the body, and will therefore support publishing verification results.

Here's how the ruby implementation does it: https://github.com/pact-foundation/pact-ruby/blob/da2facf26dbefbb52cc1b6553a4eafe6b4675f46/lib/pact/provider/verification_results/publish.rb#L47

Is it not possible to inspect the content of the pact with the ffi library? Can we expose a function to do this if not?

**Comment by adamrodger** [comment] 2022-06-03 09:10
The FFI could certainly do that internally. It'd need quite a bit of refactoring though because publishing results is currently based on the source used rather than anything inside the content itself.

That's good to know though, thanks.

**Comment by adamrodger** [comment] 2022-06-05 13:57
Raised tracking issue https://github.com/pact-foundation/pact-reference/issues/199 for the required FFI enhancements to support this.

**Comment by xeroeugene** [comment] 2022-07-06 02:43
@adamrodger seems like FFI fix has been released now.

**Closed** 2022-07-13 09:38 UTC
Labels: enhancement, feature request, ffi

**Comment by adamrodger** [comment] 2022-07-14 19:19
It's in 4.1.0

**Comment by dhvOS** [comment] 2022-07-19 14:49
I have also faced that issue

**Comment by dhvOS** [comment] 2022-08-05 15:16
Hi @adamrodger , is there any news about the issue described by @RobertGilmour? Have you been able to reproduced it on your side?
